
<body>
<div >
        <h1 class="centrer">Bienvenue chez les Swappistes !</h1>
        <p class="gras centrer" >Le premier site d'échange en ligne</p>
        <p class="centrer">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore nihil voluptatum atque! Ratione odio fuga nisi voluptate praesentium quisquam distinctio quaerat natus doloremque? Voluptatum velit consequatur doloribus neque rem expedita reiciendis est a earum! Deserunt impedit beatae repudiandae, ducimus voluptas labore nemo cupiditate! Officiis tempora quos minus beatae labore error. Illum delectus cum suscipit dolores ullam eos aliquam? Placeat animi vel sapiente exercitationem, labore necessitatibus facilis, porro ad optio sint praesentium ex soluta veritatis eum ipsa inventore temporibus iusto, ab quo natus? Rerum ea vero quam! Quia soluta voluptas, repudiandae nostrum aut voluptatem incidunt perspiciatis, nulla perferendis reiciendis temporibus, rem ipsam eligendi doloremque. Vitae possimus rem expedita consequatur? Nesciunt ab aliquam incidunt perspiciatis accusantium. Sunt saepe qui, earum neque nesciunt adipisci quam temporibus ut laudantium perferendis, dolor, optio maiores a. Hic facilis, distinctio repellat fugit suscipit eaque nulla adipisci porro nobis! Itaque cupiditate fuga quibusdam nam nostrum fugiat accusamus libero alias praesentium asperiores laborum facere id voluptas, natus, ea blanditiis facilis, vitae adipisci similique! Omnis qui architecto iste eos debitis, harum ad nemo commodi voluptas est obcaecati ex laboriosam tempore illo quod eligendi voluptatum velit enim eveniet? Corporis placeat facere deleniti quo dicta impedit? Neque dolorem blanditiis iure hic. Repellat corporis numquam temporibus optio, fuga omnis, iusto culpa sunt vitae et odit, repudiandae dolor consectetur. Iure ducimus sint iusto quibusdam sunt asperiores ullam eligendi, quia, minima a exercitationem, maiores recusandae? Ea nobis fugit inventore tempora dicta placeat dolorem doloremque pariatur libero, voluptate impedit rerum! Repellat, veritatis maiores laudantium dicta voluptatibus ab optio aspernatur animi, libero officia excepturi soluta minima officiis placeat. Similique minus tenetur exercitationem illo eius! Corporis at minus in nulla dignissimos pariatur delectus, inventore excepturi aut deleniti, aliquid necessitatibus sunt similique hic, perferendis doloribus! Laboriosam recusandae atque quae eligendi voluptatum quasi sint suscipit nisi. Porro molestias officiis dolorem!</p>

    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="bootstrap.min.js"></script>
</body>
</html>